### ISSUE TITLE
README_zh.md file 

### ISSUE THREAD

**Issue by FengCheng-Space** [wyysf-98/CraftsMan3D#34]
In README_zh.md file, Spelling 'wget' error in：
"## 您可以直接使用 wget 下载:
wegt https://huggingface.co/craftsman3d/craftsman-v1-5/blob/main/config.yaml
wegt https://huggingface.co/craftsman3d/craftsman-v1-5/blob/main/model.ckpt"

**Comment by wyysf-98** [comment]
HI， I updated the new README.
